name: Pudink

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PDM ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ matrix.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit action
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose

      - name: Run tests
        run: pdm run pytest

      - name: Create client executable ${{ matrix.os }} ${{ matrix.python-version }}
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: ${{ matrix.python-version }}
          spec: 'src/pudink/client/__main__.py'
          upload_exe_with_name: 'pudink-${{ matrix.os }}'
          options: --onefile, --name "pudink", --windowed,
